[flaskers]
flask1 ansible_host=32.192.196.131 ansible_user=ubuntu ansible_ssh_private_key_file=/home/joaoribeiro/Key_Secrets/Joao-useast1.pem
flask2 ansible_host=18.206.254.72 ansible_user=ubuntu ansible_ssh_private_key_file=/home/joaoribeiro/Key_Secrets/Joao-useast1.pem