---
- name: 2 – Clone repo
  hosts: flaskers
  tasks:
    - name: Ensure git is present
      ansible.builtin.apt:
        name: git
        state: present
        update_cache: yes
      become: true
 
    - name: Clone Flaskerino
      ansible.builtin.git:
        repo: https://github.com/professordiogodev/devops.flaskerino.git
        dest: /opt/flaskerino
        version: main
      become: true