---
- name: 3 – Python & packages
  hosts: flaskers
  become: true
  tasks:
    - name: Install Python, pip, virtualenv
      ansible.builtin.apt:
        name:
          - python3
          - python3-pip
          - python3-venv
        state: present
        update_cache: true
 
    - name: Create virtualenv
      ansible.builtin.command: python3 -m venv /opt/flaskerino/venv
      args:
        creates: /opt/flaskerino/venv
 
    - name: Install requirements
      ansible.builtin.pip:
        requirements: /opt/flaskerino/requirements.txt
        virtualenv: /opt/flaskerino/venv